[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/hello"
  to = "/.netlify/functions/hello"

[[redirects]]
  from = "/image/uploadfile"
  to = "/.netlify/functions/image"

[[redirects]]
  from = "/image/uploadfiles"
  to = "/.netlify/functions/image"